FROM node:22-alpine AS dev

WORKDIR /app

# Copies packages, files and install dependencies
COPY package*.json ./
RUN npm ci

# Copies the rest of the source code
COPY . .

# Exposes the Vite development server port
EXPOSE 5173

CMD ["npm", "run", "dev"]